import type { FunctionalComponent } from 'vue'
import {
  PaperClipIcon,
  UserIcon,
  UserCircleIcon,
  ArrowRightEndOnRectangleIcon,
  HomeIcon,
  AcademicCapIcon,
  BuildingLibraryIcon,
  MapPinIcon,
  GlobeAltIcon,
  LinkIcon,
  IdentificationIcon,
  LockClosedIcon,
  EnvelopeIcon,
  KeyIcon,
  InformationCircleIcon,
  CheckCircleIcon,
  ExclamationTriangleIcon,
  XCircleIcon,
  XMarkIcon,
  MagnifyingGlassIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronRightIcon,
  ArrowPathIcon,
  ArrowLeftIcon,
  PlusIcon,
  ArrowUpTrayIcon,
  ArrowDownTrayIcon,
  ArrowTopRightOnSquareIcon,
  TrashIcon,
  DocumentDuplicateIcon,
  CheckIcon,
  BoltIcon,
  SparklesIcon,
  ScaleIcon,
  CircleStackIcon,
  QueueListIcon,
  FolderIcon,
  UsersIcon,
  UserPlusIcon,
  Bars3Icon,
  SunIcon,
  MoonIcon,
  CodeBracketIcon,
} from '@heroicons/vue/24/outline'

/**
 * 图标注册表：业务用的语义名 → heroicons 组件。
 * 抽成独立模块（而非塞在 SvgIcon.vue 里）是为了导出 {@link IconType} 联合类型，
 * 让任何传 `type` 的地方都能在编译期校验图标名（拼错即报错，而非静默回退问号）。
 */
export const ICON_MAP = {
  user: UserIcon,
  'user-circle': UserCircleIcon,
  signin: ArrowRightEndOnRectangleIcon,
  link: LinkIcon,
  home: HomeIcon,
  research: AcademicCapIcon,
  institution: BuildingLibraryIcon,
  position: MapPinIcon,
  region: GlobeAltIcon,
  'id-card': IdentificationIcon,
  password: LockClosedIcon,
  email: EnvelopeIcon,
  verify_code: KeyIcon,
  // Toast / status
  info: InformationCircleIcon,
  success: CheckCircleIcon,
  warning: ExclamationTriangleIcon,
  error: XCircleIcon,
  // Common UI
  search: MagnifyingGlassIcon,
  chevron_down: ChevronDownIcon,
  chevron_up: ChevronUpIcon,
  chevron_right: ChevronRightIcon,
  plus: PlusIcon,
  upload: ArrowUpTrayIcon,
  download: ArrowDownTrayIcon,
  refresh: ArrowPathIcon,
  back: ArrowLeftIcon,
  share: ArrowTopRightOnSquareIcon,
  trash: TrashIcon,
  duplicate: DocumentDuplicateIcon,
  check: CheckIcon,
  bolt: BoltIcon,
  sparkles: SparklesIcon,
  scale: ScaleIcon,
  close: XMarkIcon,
  circle_stack: CircleStackIcon,
  queue_list: QueueListIcon,
  folder: FolderIcon,
  users: UsersIcon,
  user_plus: UserPlusIcon,
  bars3: Bars3Icon,
  sun: SunIcon,
  moon: MoonIcon,
  'paper-clip': PaperClipIcon,
  'code-bracket': CodeBracketIcon,
} satisfies Record<string, FunctionalComponent>

/** 所有合法图标名的联合类型，供 SvgIcon 的 `type` 及各处图标字段引用 */
export type IconType = keyof typeof ICON_MAP
