<script setup lang="ts">
import { computed } from 'vue';
import {
	UserIcon,
	UserCircleIcon,
	ArrowRightEndOnRectangleIcon,
	HomeIcon,
	AcademicCapIcon,
	BuildingLibraryIcon,
	MapPinIcon,
	GlobeAltIcon,
	LinkIcon,
	IdentificationIcon,
	LockClosedIcon,
	EnvelopeIcon,
	KeyIcon,
	QuestionMarkCircleIcon,
	InformationCircleIcon,
	CheckCircleIcon,
	ExclamationTriangleIcon,
	XCircleIcon,
	XMarkIcon,
	MagnifyingGlassIcon,
	ChevronDownIcon,
	ChevronUpIcon,
	ArrowPathIcon,
	ArrowLeftIcon,
	PlusIcon,
	ArrowUpTrayIcon,
	ArrowDownTrayIcon,
	ArrowTopRightOnSquareIcon,
	TrashIcon,
	DocumentDuplicateIcon,
	CheckIcon,
	BoltIcon,
	SparklesIcon,
	ScaleIcon,
	CircleStackIcon,
	QueueListIcon,
	FolderIcon,
	UsersIcon,
	UserPlusIcon,
	Bars3Icon,
	SunIcon,
	MoonIcon,
} from '@heroicons/vue/24/outline';


const props = defineProps<{ type: string }>();

const ICON_MAP: Record<string, any> = {
	user: UserIcon,
	'user-circle': UserCircleIcon,
	signin: ArrowRightEndOnRectangleIcon,
	link: LinkIcon,
	home: HomeIcon,
	research: AcademicCapIcon,
	institution: BuildingLibraryIcon,
	position: MapPinIcon,
	region: GlobeAltIcon,
	'id-card': IdentificationIcon,
	password: LockClosedIcon,
	email: EnvelopeIcon,
	verify_code: KeyIcon,
	// Toast / status
	info: InformationCircleIcon,
	success: CheckCircleIcon,
	warning: ExclamationTriangleIcon,
	error: XCircleIcon,
	// Common UI
	search: MagnifyingGlassIcon,
	chevron_down: ChevronDownIcon,
	chevron_up: ChevronUpIcon,
	plus: PlusIcon,
	upload: ArrowUpTrayIcon,
	download: ArrowDownTrayIcon,
	refresh: ArrowPathIcon,
	back: ArrowLeftIcon,
	share: ArrowTopRightOnSquareIcon,
	trash: TrashIcon,
	duplicate: DocumentDuplicateIcon,
	check: CheckIcon,
	bolt: BoltIcon,
	sparkles: SparklesIcon,
	scale: ScaleIcon,
	close: XMarkIcon,
	circle_stack: CircleStackIcon,
	queue_list: QueueListIcon,
	folder: FolderIcon,
	users: UsersIcon,
	user_plus: UserPlusIcon,
	bars3: Bars3Icon,
	sun: SunIcon,
	moon: MoonIcon,
};

const IconComp = computed(() => ICON_MAP[props.type] || QuestionMarkCircleIcon);
</script>

<template>
	<component v-bind="$attrs" :is="IconComp" class="inline-block" aria-hidden="true" />
</template>
