/**
 * 离线图标打包用的清单：唯一的真相来源。
 * 新增图标用法时，把图标名加到对应集合里，然后跑 `npm run icons:bundle` 重新生成
 * src/shared/icons/iconBundle.generated.json。
 */
export const ICON_SETS = {
  heroicons: [
    'paper-clip',
    'user',
    'user-circle',
    'arrow-right-end-on-rectangle',
    'home',
    'academic-cap',
    'building-library',
    'map-pin',
    'globe-alt',
    'link',
    'identification',
    'lock-closed',
    'envelope',
    'key',
    'information-circle',
    'check-circle',
    'exclamation-triangle',
    'x-circle',
    'x-mark',
    'magnifying-glass',
    'chevron-down',
    'chevron-up',
    'chevron-left',
    'chevron-right',
    'arrow-path',
    'arrow-left',
    'plus',
    'minus',
    'pencil',
    'arrow-up-tray',
    'arrow-down-tray',
    'arrow-top-right-on-square',
    'trash',
    'document-duplicate',
    'check',
    'bolt',
    'sparkles',
    'scale',
    'circle-stack',
    'queue-list',
    'folder',
    'users',
    'user-plus',
    'bars-3',
    'sun',
    'moon',
    'code-bracket',
    'question-mark-circle',
    'user-group',
    'arrow-trending-up',
    'cpu-chip',
    'book-open',
  ],
  'simple-icons': ['github', 'wechat', 'alibabacloud'],
  lucide: ['lasso', 'square'],
}
